sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t parsaudarmil/docker-react  -f Dockerfile.dev .
script:
  - docker run -e CI=true parsaudarmil/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "doker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-334782212675"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
